# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: James Armes
pronouns: they/them
author: James Armes (they/them)
email: jamesiarmes@gmail.com
description: >-
  Solutions Engineer @ Code for America.
  Developing technical solutions to problems that affect real people.
logo: /assets/img/me-round.png
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.jamesarmes.com
google_analytics: G-0BTVLDC8EC
favicon: /assets/favicon.png

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github" title="GitHub"></i>
    link: https://github.com/jamesiarmes
  - name: Keybase
    icon: <i class="fa-brands fa-keybase" title="Keybase"></i>
    link: https://keybase.io/jamesiarmes
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin" title="LinkedIn"></i>
    link: https://www.linkedin.com/in/jamesiarmes
  - name: Mastodon
    icon: <i class="fa-brands fa-mastodon" title="Mastodon"></i>
    link: https://tech.lgbt/@jamesiarmes
  - name: Drupal
    icon: <i class="fa-brands fa-drupal" title="Drupal"></i>
    link: https://www.drupal.org/u/bassistjimmyjam
  - name: Dev.to
    icon: <i class="fa-brands fa-dev" title="Dev.to"></i>
    link: https://dev.to/jamesiarmes
  - name: RSS
    icon: <i class="fa-solid fa-rss" title="RSS feed"></i>
    link: /feed.xml

# Build settings
markdown: kramdown
theme: jekyll-theme-minimalistic
permalink: /:year/:month/:title.html
plugins:
  - jekyll-feed
  - jekyll-glossary_tooltip
  - jekyll-paginate-v2
#  - jekyll_picture_tag
  - jekyll-tagging-lite

tag_page_layout: tag
tag_page_dir: tags
tag_page_data:
  sitemap: false

# Exclude from processing.
exclude:
  - .github/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - oldsite

navigation:
  - name: Home
    link: /
    icon: <i class="fa-solid fa-house"></i>
  - name: About
    link: /about.html
    icon: <i class="fa-solid fa-person-half-dress"></i>
  - name: Posts
    link: /posts
    icon: <i class="fa-solid fa-signs-post"></i>
  - name: Presentations
    link: /presentations.html
    icon: <i class="fa-solid fa-person-chalkboard"></i>

pagination:
  enabled: true
  collection: posts
  sort_reverse: true
  per_page: 10
  permalink: '/page/:num/'
  title: 'page :num'
  category: blog
  limit: 0
  trail:
    before: 2
    after: 2
