plugins:
  - jekyll-remote-theme
remote_theme: le4ker/personal-jekyll-theme

# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https:/www.jamesarmes.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: "UA-3412924-2"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############
lang: "en"
author: "James Armes"
title: "{ James Armes }"
description: "Blog and website of James Armes, blogging mainly for tech. Opinions expressed are mine."
keywords: "armes, james, personal, software, engineering, development, programming"
favicon: "/img/favicon.ico"

################
# Header layout #
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
